# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
        migrations.AddField(
            model_name='competition',
            name='drone',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='drones.Drone'),
            preserve_default=False,
        ),
    ]
